name: Add a Paper
description: Suggest a new paper for the Awesome List
title: "[Paper]: <Title>"
labels: ["paper"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your contribution! Please follow the format below.
  
  - type: input
    id: title
    attributes:
      label: Paper Title
      description: The full title of the paper.
      placeholder: e.g., "Generative Visual Code Mobile World Models"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link (ArXiv / PDF)
      description: URL to the paper (preferably ArXiv abstract page).
      placeholder: https://arxiv.org/abs/2602.XXXXX
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date (YYYY-MM)
      description: Publication date.
      placeholder: 2026-02
    validations:
      required: true

  - type: input
    id: code
    attributes:
      label: Code Link (Optional)
      description: GitHub URL if available.
      placeholder: https://github.com/username/repo
    validations:
      required: false

  - type: textarea
    id: comment
    attributes:
      label: Additional Comments
      description: Anything else you want to say? (e.g. why this paper is relevant)
    validations:
      required: false
